# Generated by Django 4.2.4 on 2023-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_esfirras_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
